///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest4Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("cf3e02e8-344f-4a22-9641-41ef1f17827f")]
    public partial class MyTest4Repository : RepoGenBaseFolder
    {
        static MyTest4Repository instance = new MyTest4Repository();
        MyTest4RepositoryFolders.InusikbRxTestRepositoryGoogleChromAppFolder _inusikbrxtestrepositorygooglechrom;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest4Repository element repository.
        /// </summary>
        [RepositoryFolder("cf3e02e8-344f-4a22-9641-41ef1f17827f")]
        public static MyTest4Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest4Repository() 
            : base("MyTest4Repository", "/", null, 0, false, "cf3e02e8-344f-4a22-9641-41ef1f17827f", ".\\RepositoryImages\\MyTest4Repositorycf3e02e8.rximgres")
        {
            _inusikbrxtestrepositorygooglechrom = new MyTest4RepositoryFolders.InusikbRxTestRepositoryGoogleChromAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cf3e02e8-344f-4a22-9641-41ef1f17827f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The InusikbRxTestRepositoryGoogleChrom folder.
        /// </summary>
        [RepositoryFolder("8acbf742-c72e-4773-b7da-c7901d20088f")]
        public virtual MyTest4RepositoryFolders.InusikbRxTestRepositoryGoogleChromAppFolder InusikbRxTestRepositoryGoogleChrom
        {
            get { return _inusikbrxtestrepositorygooglechrom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MyTest4RepositoryFolders
    {
        /// <summary>
        /// The InusikbRxTestRepositoryGoogleChromAppFolder folder.
        /// </summary>
        [RepositoryFolder("8acbf742-c72e-4773-b7da-c7901d20088f")]
        public partial class InusikbRxTestRepositoryGoogleChromAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element199427872Info;

            /// <summary>
            /// Creates a new InusikbRxTestRepositoryGoogleChrom  folder.
            /// </summary>
            public InusikbRxTestRepositoryGoogleChromAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InusikbRxTestRepositoryGoogleChrom", "/form[@title~'^inusikb/rx_TestRepository']", parentFolder, 30000, null, true, "8acbf742-c72e-4773-b7da-c7901d20088f", "")
            {
                _element199427872Info = new RepoItemInfo(this, "Element199427872", "element[@controlid='199427872']", 30000, null, "6427b092-ce60-48ce-a50b-5db7241ac767");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8acbf742-c72e-4773-b7da-c7901d20088f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8acbf742-c72e-4773-b7da-c7901d20088f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element199427872 item.
            /// </summary>
            [RepositoryItem("6427b092-ce60-48ce-a50b-5db7241ac767")]
            public virtual Ranorex.Unknown Element199427872
            {
                get
                {
                    return _element199427872Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element199427872 item info.
            /// </summary>
            [RepositoryItemInfo("6427b092-ce60-48ce-a50b-5db7241ac767")]
            public virtual RepoItemInfo Element199427872Info
            {
                get
                {
                    return _element199427872Info;
                }
            }
        }

    }
#pragma warning restore 0436
}